- hosts: web
  vars:
    nginx_port: 8070
    root_dir: /usr/share/nginx/html/

  tasks:
    - name: nginx install
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes

    - name: copy index.html
      ansible.builtin.copy:
        src: ./files/index.html
        dest: "{{root_dir}}index.html"
      become: yes

    - name: copy nginx.conf
      ansible.builtin.template:
        src: ./files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
    



  