- hosts: dev
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: init

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: init

    - name: install nginx
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: init

    - name: create user arya
      ansible.builtin.user:
        name: "arya"
      become: yes
      tags: users

    - name: create user tirion
      ansible.builtin.user:
        name: "tirion"
      become: yes
      tags: users

